### ISSUE TITLE
C++ Port

### ISSUE THREAD

**Issue by Jochengehtab** [david-carteau/cerebrum#3]
Hi there,
I am currently trying to implement your library into a c++ chess engine and find it a bit difficult to get everything to work. Like it is a problem to load the nnue file in the c++ code base.

**Comment by david-carteau** [comment]
Hi, sorry for the late reply! Could you perhaps share a piece of code? Have you managed to train your own network and have you generated an "epoch-5.txt" file at the end of the training (remember to rename it to "network.txt")?
